name: aws_demo
channels:
  - conda-forge
  - defaults
dependencies:
  - bokeh
  - holoviews
  - numpy
  - pandas
  - panel
  - parquet
  - jupyterlab
  - pip
  - pyarrow
  - pyviz_comms=2.1.0
  - spacy
  - datasets
  - scikit-learn