name: vector-2
channels:
  - conda-forge
  - defaults
dependencies:
  - arrow-cpp=4.0.1
  - bokeh
  - holoviews=1.14.4
  - numpy=1.21.1
  - pandas=1.3.0
  - panel=0.11.3
  - param
  - parquet-cpp=1.5.1
  - jupyterlab
  - pip=21.1.3
  - pyarrow=4.0.1
  - pyviz_comms=2.1.0
  - ipykernel
  - scikit-learn=0.24.2
  - pip:
    - spacy==3.1.1
    - datasets
